version: 2
jobs:
  test:
    docker:
      - image: rust:1.52
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ .Branch }}
            - v1-cargo-cache-{{ arch }}
      - run:
          name: Show versions
          command: rustc --version && cargo --version
      - run:
          name: Build
          command: cargo build
      - run:
          name: Run tests
          command: cargo test
      - save_cache:
          key: v1-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
      - save_cache:
          key: v1-cargo-cache-{{ arch }}
          paths:
            - target
            - /usr/local/cargo
  lint:
    docker:
      - image: rust:1.52
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cargo-lint-cache
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - save_cache:
          key: v1-cargo-lint-cache
          paths:
            - /usr/local/cargo
  audit:
    docker:
      - image: dbrgn/cargo-audit
    steps:
      - checkout
      - run:
          name: Run cargo audit
          command: cargo audit

workflows:
  version: 2

  # Build on push
  on_push:
    jobs:
      - test
      - lint
      - audit
